### ISSUE TITLE
Add Faveicon to the Book

### ISSUE THREAD

**Issue by rupsis** [RayTracing/gpu-tracing#6]
The book needs a Favicon. 

He's a very simple suggestion based on the vertex/rasterization step of the pipeline: 
![gpu_faveicon](https://github.com/RayTracing/gpu-tracing/assets/9646385/f591e44b-9578-4a76-a8c7-8a2f571184da)

**Comment by armansito** [comment]
I like it! The rasterization step technically plays a very small role in the overall design of the renderer (it's effectively there to put the ray traced pixels on the framebuffer) but GPUs do triangles and I like this as a favicon.

Would you like to open a PR that sets up the favicon?

**Comment by rupsis** [comment]
Yeah I'll go ahead and create a PR for it.

**Comment by rupsis** [comment]
Addressed in #7
